### ISSUE TITLE
hey everyone thread '<unnamed>' panicked at 'assertion failed: `(left == right)` error when I run command 'yarn dev'

### ISSUE THREAD

**Issue by jianvector** [straightupjac/nft-merkle-whitelist-scaffold#4]
**Describe the bug**
[root@VM-0-15-centos web]# yarn dev
yarn run v1.22.17
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /root/NFT/nft-merkle-whitelist-scaffold/web/.env
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `0`', library/std/src/sys/unix/condvar.rs:63:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:393:21
thread '<unnamed>' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:393:21
thread '<unnamed>' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:393:21
thread '<unnamed>' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:393:21
thread '<unnamed>' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:393:21
thread '<unnamed>' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:393:21
thread '<unnamed>' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:393:21
error - ./node_modules/next/dist/client/dev/amp-dev.js
Error: failed to process
^C
[root@VM-0-15-centos web]# yarn build
yarn build
yarn run v1.22.17
$ next build
info  - Loaded env from /root/NFT/nft-merkle-whitelist-scaffold/web/.env
info  - Checking validity of types
info  - Creating an optimized production build ..thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `0`', library/std/src/sys/unix/condvar.rs:63:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:393:21
thread '<unnamed>' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:393:21
thread '<unnamed>' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:393:21
thread '<unnamed>' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:393:21
thread '<unnamed>' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:393:21
thread '<unnamed>' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:393:21
info  - Creating an optimized production build
Failed to compile.

./node_modules/next/dist/client/next.js
Error: failed to process assertion failed: `(left == right)`
  left: `22`,
 right: `0`

./node_modules/next/dist/client/router.js
Error: failed to process

./node_modules/next/dist/pages/_error.js
Error: failed to process

./pages/_app.js
Error: failed to process

./pages/index.js
Error: failed to process

> Build failed because of webpack errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by straightupjac** [comment]
Hey! This is likely because you have an empty .env variable or something missing from there
